In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [42]:
import numpy as np
import pandas as pd

In [7]:
# some dummy data with shape (5,3,2)
dummy_data = np.asarray([
    [[1,2], [1,1], [2,1]],
    [[3,1], [4,1], [5,2]],
    [[0,1], [0,1], [1,2]],
    [[-1,-2], [-1,-1], [-2,-1]],
    [[0,-3], [-1,-4], [0,-2]],
])

In [10]:
dummy_labels = [0,0,1,1,2]

In [17]:
np.concatenate([np.repeat(label, dummy_data.shape[1]) for label in dummy_labels])

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2])

In [56]:
def make_table(data, labels):
    
    if not isinstance(data, np.ndarray):
        data = np.asarray(data)
    if not isinstance(labels, np.ndarray):
        labels = np.asarray(labels)
        
    num_pts, num_samples, num_dim = data.shape
    
    ids = np.arange(num_pts).repeat(num_samples)
    labels = labels.repeat(num_samples)
    coords = data.reshape(-1, num_dim).transpose()
    samples = np.tile(np.arange(num_samples), num_pts)
    
    data_dict = {
        'id': ids,
        'label': labels,
        'sample': samples
    }
    
    for dim, xs in enumerate(coords):
        data_dict['x' + str(dim)] = xs
        
    return pd.DataFrame(data=data_dict)

In [57]:
df = make_table(dummy_data, dummy_labels)

In [70]:
df[df.id == 2]

id  label  sample  x0  x1
6   2      1       0   0   1
7   2      1       1   0   1
8   2      1       2   1   2

In [83]:
df[df.id == 2].drop(['id','label', 'sample'], axis=1).values

array([[0, 1],
       [0, 1],
       [1, 2]])

In [97]:
[len(df[df['label'] == i]) // 3 for i in set(df['label'].values)]

[2, 2, 1]

In [88]:
len(set(dummy_labels))

3

In [112]:
import labeledclusters as lc

In [189]:
foo = lc.LabeledSampledOutputs(dummy_data, dummy_labels)

In [190]:
foo.get_instance_cluster(3).data

array([[-1, -2],
       [-1, -1],
       [-2, -1]])

In [130]:
dummy_data

array([[[ 1,  2],
        [ 1,  1],
        [ 2,  1]],

       [[ 3,  1],
        [ 4,  1],
        [ 5,  2]],

       [[ 0,  1],
        [ 0,  1],
        [ 1,  2]],

       [[-1, -2],
        [-1, -1],
        [-2, -1]],

       [[ 0, -3],
        [-1, -4],
        [ 0, -2]]])

In [288]:
foo.mean_overlap(4,1)

0.0014023414082622624

In [295]:
foo.overlap_map((-2,2,10),(-2,2,0.1),0.5)

[]


array([], shape=(0, 0), dtype=float64)

In [164]:
df[ ]

id  label  sample  x0  x1
0    0      0       0   1   2
1    0      0       1   1   1
2    0      0       2   2   1
3    1      0       0   3   1
4    1      0       1   4   1
5    1      0       2   5   2
12   4      2       0   0  -3
13   4      2       1  -1  -4
14   4      2       2   0  -2

In [177]:
bar = {'x':1, 'y':2, 'z':3}

In [181]:
list(bar.values())

[1, 2, 3]

In [249]:
baz = [
    [[1],[1],[1]],
    [[1],[1],[1]],
    [[10],[10],[10]],
    [[10],[10],[10]]
]

In [250]:
bazoo = [1,1,2,2]

In [290]:
test = lc.LabeledSampledOutputs(baz, bazoo)

In [292]:
test.mean_overlap(0,2)

Overlap currently only implemented for 2 dimensional clusters!


nan