In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [42]:
import numpy as np
import pandas as pd

In [7]:
# some dummy data with shape (5,3,2)
dummy_data = np.asarray([
    [[1,2], [1,1], [2,1]],
    [[3,1], [4,1], [5,2]],
    [[0,1], [0,1], [1,2]],
    [[-1,-2], [-1,-1], [-2,-1]],
    [[0,-3], [-1,-4], [0,-2]],
])

In [10]:
dummy_labels = [0,0,1,1,2]

In [17]:
np.concatenate([np.repeat(label, dummy_data.shape[1]) for label in dummy_labels])

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2])

In [56]:
def make_table(data, labels):
    
    if not isinstance(data, np.ndarray):
        data = np.asarray(data)
    if not isinstance(labels, np.ndarray):
        labels = np.asarray(labels)
        
    num_pts, num_samples, num_dim = data.shape
    
    ids = np.arange(num_pts).repeat(num_samples)
    labels = labels.repeat(num_samples)
    coords = data.reshape(-1, num_dim).transpose()
    samples = np.tile(np.arange(num_samples), num_pts)
    
    data_dict = {
        'id': ids,
        'label': labels,
        'sample': samples
    }
    
    for dim, xs in enumerate(coords):
        data_dict['x' + str(dim)] = xs
        
    return pd.DataFrame(data=data_dict)

In [57]:
df = make_table(dummy_data, dummy_labels)

In [70]:
df[df.id == 2]

id  label  sample  x0  x1
6   2      1       0   0   1
7   2      1       1   0   1
8   2      1       2   1   2

In [83]:
df[df.id == 2].drop(['id','label', 'sample'], axis=1).values

array([[0, 1],
       [0, 1],
       [1, 2]])

In [97]:
[len(df[df['label'] == i]) // 3 for i in set(df['label'].values)]

[2, 2, 1]

In [88]:
len(set(dummy_labels))

3

In [112]:
import labeledclusters as lc

In [189]:
foo = lc.LabeledSampledOutputs(dummy_data, dummy_labels)

In [190]:
foo.get_instance_cluster(3).data

array([[-1, -2],
       [-1, -1],
       [-2, -1]])

In [130]:
dummy_data

array([[[ 1,  2],
        [ 1,  1],
        [ 2,  1]],

       [[ 3,  1],
        [ 4,  1],
        [ 5,  2]],

       [[ 0,  1],
        [ 0,  1],
        [ 1,  2]],

       [[-1, -2],
        [-1, -1],
        [-2, -1]],

       [[ 0, -3],
        [-1, -4],
        [ 0, -2]]])

In [288]:
foo.mean_overlap(4,1)

0.0014023414082622624

In [181]:
list(bar.values())

[1, 2, 3]

In [249]:
baz = [
    [[1],[1],[1]],
    [[1],[1],[1]],
    [[10],[10],[10]],
    [[10],[10],[10]]
]

In [250]:
bazoo = [1,1,2,2]

In [290]:
test = lc.LabeledSampledOutputs(baz, bazoo)

In [292]:
test.mean_overlap(0,2)

Overlap currently only implemented for 2 dimensional clusters!


nan

In [298]:
df.sample(5)

id  label  sample  x0  x1
14   4      2       2   0  -2
4    1      0       1   4   1
2    0      0       2   2   1
9    3      1       0  -1  -2
1    0      0       1   1   1

In [305]:
np.random.randint(0,100,size=200)

array([40, 52, 11, 55, 51, 99, 33, 74,  6, 87, 89, 63, 26, 37, 48, 78, 16,
       26, 98, 19, 21, 38, 56, 40, 18, 16, 52, 41, 67, 83, 94, 71, 57,  4,
       53, 71, 33,  2, 26, 24, 15,  9, 91, 82, 53, 49, 80, 74,  3, 60, 82,
       14, 60,  4, 42, 44, 70, 34, 93,  4, 21, 44, 53, 62, 72, 11, 58, 20,
        7, 96, 18, 23, 56, 99, 67, 97, 78, 49, 13, 73, 64, 82,  8, 19,  5,
       43,  4, 67, 24, 53, 81, 24, 11, 27, 65, 11, 34, 94, 12, 24, 13, 67,
       17, 79, 20, 37, 77,  1, 38, 50, 16, 93, 17, 20, 28, 38,  2, 54, 68,
       97, 60,  7, 15, 79, 59, 67, 47, 87,  6, 44,  5, 39, 36, 88, 62, 69,
       81, 32,  8, 31,  4,  5, 48, 72, 83, 60, 12, 68, 63, 20, 73, 77,  4,
       91, 75, 80, 75, 30, 92, 26, 35, 98, 18, 67, 24, 73, 35, 18, 12, 39,
       21, 46, 55, 74, 29, 47, 82, 72, 14, 61,  5, 78,  8, 91, 64, 55, 96,
       37,  2, 12, 45, 70, 69, 27, 42, 21, 71, 65, 72, 51])

In [323]:
np.random.seed(None)

In [324]:
np.random.rand()

0.4413238444591616

In [328]:
np.random.choice([1,2,3,4,5,6,7,8,9],size=12, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [345]:
foo.index_dict()

{0: array([0, 1]), 1: array([2, 3]), 2: array([4])}

In [334]:
print(x)

None


In [354]:
[i for i in foo.instances_per_class().values()]

[2, 2, 1]

In [357]:
np.array([1,2,3,4,5,6,7,8,9])[np.array([1,4,7])]

array([2, 5, 8])

In [371]:
foo.random_subset(1, per_class=True)

(array([0, 2, 4]), array([[[ 1,  2],
         [ 1,  1],
         [ 2,  1]],
 
        [[ 0,  1],
         [ 0,  1],
         [ 1,  2]],
 
        [[ 0, -3],
         [-1, -4],
         [ 0, -2]]]))